env:
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER autoconf
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - ghc --version

script:
 - autoreconf -i
 - cabal-1.18 configure -v2
 - cabal-1.18 build
 - cabal-1.18 check
 - cabal-1.18 sdist
 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal-1.18 install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi